### PR TITLE
ExpressJS action

### PR DESCRIPTION
**Pull request by mintuz**
Calling the CLI tool with `node index.js express` allows you to send POST requests to `localhost:3000` with the body

```

# Native commands
{"mode":"sphero", "action":"color", "value": "yellow"}

# Custom Commands
{"mode":"custom", "action":"disco"}
```

where command can be any of the bb8/sphero functions and value is either a string or an array of parameters passed to that function.

By itself this is probably a little useless but it allows for IFTTT integration and HTML5 canvas controls.

### CODE REVIEW

**Comment by JBX028** [comment]
Hi,
This is definitively a good idea to expose the commands as rest webservices but when I run the command, my device is connected for a second or 2 and then automatically disconnected and therefore I cannot submit any request (command invalid is returned).
Several weeks ago, I also tried to create my own service with npm restify and I was face to the same mistake while I can easily control my bb8 with other scripts available in github.
Does at mean you aren't face to the same issue than me?

**Comment by mintuz** [comment]
Hello @JBX028 that might be my fault. I made a change before to allow for us to create custom commands like "disco" or "weather". You need to pass an extra key value pair so your request body would look like this.

```
{"mode":"sphero", "command":"color", "value": "yellow"}
```

Let me know if that works. Just tried it out and its working for me ok.

**Comment by JBX028** [comment]
Hi,

No more luck unfortunately. When I run the server (sudo node index.js express) by BB8 blinks in red for 2 seconds and then becomes orange and then seems to be off. This is what is visible in the console that mean everything looks good:

Connected to BB-3961
Server listening on port 3000

Does your BB8 stays in red once the server is started?

Thanks

**Comment by mintuz** [comment]
That could be a couple of things.
1. You shouldn't need to run it as sudo, might be doing something odd with the permissions accessing the Bluetooth adapter
2. Might be a noddy question, but is it charged up.
3. Try running `node index.js disco` - All this does is make it change to random colours - If it doesn't work might be something with how your BB8 is connecting to your mac/pc because this is the simplest check we can do.
4. Try deleting your `~/.bb8config` file and then `node index.js disconnect` then rerun `node index.js setup`
5. What version of node are you running? 

I've not experienced this problem myself but flashing red twice means it needs charging I believe.

**Comment by mintuz** [comment]
@JBX028 Can you try pulling the branch down again, I've done some tweaks to how we handle some of the params. It should now also do custom commands so if you like... try running

```
{"mode":"custom", "command":"disco"}
```

**Comment by JBX028** [comment]
Hi,

I will try thanks! FYI I cannot run the server nore the disco plugin
without sudo (noble warning: adapter state unauthorized, please run as root
or ......)

2016-01-24 11:23 GMT+01:00 Adam Bulmer notifications@github.com:

**Comment by mintuz** [comment]
Can you run `rm -rf node_modules` then rerun `npm install` without sudo and if that fails because of permissions can you follow the steps here ... https://docs.npmjs.com/getting-started/fixing-npm-permissions.

**Comment by JBX028** [comment]
Just tried but even after having doing that, I am face to the same problem
and I have to run all scripts as system admin. I will read the document
behind the hyperlink. Thanks!

2016-01-24 11:30 GMT+01:00 Adam Bulmer notifications@github.com:

**Pull request merged**
